"""add new table

Revision ID: a3b8cb723a42
Revises: 3c7a23f9f9af
Create Date: 2023-03-22 20:47:13.294998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3b8cb723a42'
down_revision = '3c7a23f9f9af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
